:azurity_accounts:
  -
    :account_id: 382
    :identifier: "PI-62731489"
    :brand_name: "Horizant"
  -
    :account_id: 378
    :identifier: "PI-00776824"
    :brand_name: "Adthyza_HCP"
  -
    :account_id: 379
    :identifier: "PI-24621729"
    :brand_name: "Adthyza_Consumer"
  -
    :account_id: 366
    :identifier: "PI-05764704"
    :brand_name: "Triptodur"
  -
    :account_id: 381
    :identifier: "PI-08602150"
    :brand_name: "Eprontia"
  -
    :account_id: 383
    :identifier: "PI-03913254"
    :brand_name: "Zonisade"
  -
    :account_id: 384
    :identifier: "PI-35722843"
    :brand_name: "EFamily"
  -
    :account_id: 375
    :identifier: "PI-57350493"
    :brand_name: "Katerzia"
  -
    :account_id: 376
    :identifier: "PI-84827672"
    :brand_name: "Qbrelis"
  -
    :account_id: 377
    :identifier: "PI-56813408"
    :brand_name: "Nymalize"
  -
    :account_id: 410
    :identifier: "PI-98758744"
    :brand_name: "Konvomep"
  -
    :account_id: 402
    :identifier: "PI-82089830"
    :brand_name: "First Kits"
  -
    :account_id: 403
    :identifier: "PI-95963047"
    :brand_name: "Vivimusta"
  -
    :account_id: 419
    :identifier: "PI-31452599"
    :brand_name: "Myhibbin"
  -
    :account_id: 425
    :identifier: "PI-79981559"
    :brand_name: "Xatmep"
  -
    :account_id: 424
    :identifier: "PI-67585473"
    :brand_name: "Azmiro"
  -
    :account_id: 430
    :identifier: "PI-86314238"
    :brand_name: "Danziten"
  -
    :account_id: 417
    :identifier: "PI-57189780"
    :brand_name: "Solutions"

:weekly_report_worker_account_identifiers:
  - "PI-62731489"
  - "PI-00776824"
  - "PI-24621729"
  - "PI-05764704"
  - "PI-08602150"
  - "PI-03913254"
  - "PI-35722843"
  - "PI-57350493"
  - "PI-84827672"
  - "PI-56813408"
  - "PI-98758744"
  - "PI-82089830"
  - "PI-95963047"
  - "PI-31452599"
  - "PI-79981559"
  - "PI-67585473"

:adverse_event_acount_identifiers:
  - "PI-62731489"
  - "PI-95963047"
  - "PI-79981559"
  - "PI-05764704"
  - "PI-86314238"
  - "PI-57189780"
