:account_for_prepopulated_surveys : Template

:survey :
  :invitation : "You’re beautiful. Would you answer a super quick two-question survey?"
  :thank_you : "*Thank you* for your feedback!"

  :first_question :
    :content : "Question"
    :possible_answers :
      - "Answer 1"
      - "Answer 2"

  :follow_up_questions : []

  # below ones not used right now
  :possible_answers_for_flow_question_in_form :
    - 'Answer 1'
    - 'Answer 2'

  # below ones not used right now
  :trigger :
    :tooltip : 'This is a tooltip. I hope you like it.'


:tooltip :
  :widget :
    :css_selector_list : "<table><tr><td>#_pi_surveyWidgetContainer</td><td>Container of the widget. Not positioned.</td></tr>
                          <tr><td>#_pi_surveyWidget</td><td>The widget itself.</td></tr>
                          <tr><td>._pi_closeButton</td><td>The close button.</td></tr>
                          <tr><td>._pi_startButton</td><td>The start button.</td></tr>
                          <tr><td>._pi_invitationTextContainer</td><td>The container of the invitation text.</td></tr>
                          <tr><td>._pi_question</td><td>The container of the question text.</td></tr>
                          <tr><td>ul._pi_answers_container</td><td>The container of the all the position answers.</td></tr>
                          <tr><td>ul._pi_answers_container li a</td><td>Each answers link.</td></tr>
                          <tr><td>ul._pi_answers_container li a label</td><td>Each answers label.</td></tr>
                          </table>"
