default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  redis: "redis://127.0.0.1:6379"

development:
  <<: *default
  database: pi_development
  username: pi
  password:
  host: localhost
  influxdb:
    database: 'pi'
    username: ''
    password: ''
    hosts: ["127.0.0.1"]
    port: 8086
    use_ssl: false
    retry: 5

test:
  host: postgres
  username: pi
  <<: *default
  password: "mysecretpassword"
  template: template0
  database: pi_test
  redis: "redis://127.0.0.1:6379/1"
  rack-host: postgres
  influxdb:
    database: "pi_test"
    username: "root"
    password: 'admin'
    hosts: ["influxdb"]
    port: 8086
    use_ssl: false
    retry: 5

develop:
  <<: *default
  database: pi_develop
  username: pi
  password:
  host: localhost
  influxdb:
    database: 'pi'
    username: ''
    password: ''
    hosts: ["127.0.0.1"]
    port: 8086
    use_ssl: false
    retry: 5

production:
  <<: *default
  database: pi_production
  username: pi
  password: <%= ENV['PI_DATABASE_PASSWORD'] %>
