:domain: 'https://phbxd.qrveyapp.com'

:ikea_dashboard_id: "2ILZUY1UBXUvxb5XrLsOP"
:ikea_dataset_id: "ywqweemyl"

:platform_health:
  :user_id: "FU8fv5Yz0" # Brooke
  :app_id: "nFvQyYFE2" # Platform and Testing

:dashboard_builder:
  :user_id: 'XoYxNFoyo' # Pablo
  :app_id: "-d04u5atA" # Client Production

:client_reports:
  :user_id: 'XoYxNFoyo' # Pablo
  :app_id: "1Jy_HB4tj" # Master Content App
  :datasets:
    -
      :id: "fqyevfpjy" # Production | View
      :survey_id_column_id: "Lx0O6Itca"
    -
      :id: "2hclg8bsj" #Submission Caches | View
      :survey_id_column_id: "m9ANbrpMB"
    -
      :id: "xpol99xoo" # Submissions | View
      :survey_id_column_id: "VUiFSWBjL"
  :dashboards:
    -
      :display_name: "Trends"
      :id: "ttU0WJ14910vtpJn3onOf"
    -
      :display_name: "Device"
      :id: "ncg7hjQSX5bNtqD99BApS"
    -
      :display_name: "URLs"
      :id: "z1gx6iApR0mgz0tBtlBMs"
    -
      :display_name: "Media"
      :id: "YmijcIhVAAHm99HhIKViC"
    -
      :display_name: "Visit Frequency"
      :id: "AvBvwbL6Uii1L1Yb675kd"
    -
      :display_name: "Raw Data"
      :id: "JBxlCHuHqwqRbDNF8mPxU"
