regularly_analyze_free_text_answers:
  every: "10m"
  class: RegularlyAnalyzeFreeTextAnswers
  queue: default
  description: "This job will regularly analyze free text answers"

tag_automation_worker:
  # every 15 minutes
  cron: '*/15 * * * *'
  class: TagAutomationWorker
  queue: default
  description: "This job labels answers with tags through the OPEN AI API"

account_stats:
  # every hour
  cron: '0 * * * *'
  class: AccountStatsWorker
  queue: default
  description: "This job fills account_stats table with data from InfluxDB every hour"

trim_sessions:
  every: "30d"
  class: TrimSessionsWorker
  queue: default
  description: "This job will trim session every 30 days"

melee:
  every: "30m"
  class: MeleeWorker
  queue: default
  description: "This job exports Melee data every half an hour"

astra_zeneca:
  cron: '0 5 * * *'
  class: AstraZenecaWorker
  queue: console
  description: "This job sends a CSV file to S3 on a daily basis"

astra_zeneca_aggregate:
  cron: '0 13 * * *'
  class: AstraZenecaAggregateWorker
  queue: console
  description: "This job sends a CSV file of aggregated survey data to AstraZeneca's S3 on a daily basis"

free_text_translator:
  every: '5m'
  class: FreeTextTranslator
  queue: console
  description: "This job translate free text answers created within 5 minutes"

scheduled_report_checkup:
  cron: '0 23 * * *'
  class: ScheduledReportCheckupWorker
  queue: default
  description: "This job checks the status of scheduled reports and notifies us when one has failed"

# Only installed on reporting.pulseinsights
scheduled_report:
  # every 10 minutes
  cron: '*/10 * * * *'
  class: ScheduledReportWorker
  queue: default
  description: "This job processes all the upcoming scheduled reports that are not in progress"

# Only installed on reporting.pulseinsights
survey_submission_cache:
  cron: '10 */1 * * *'
  class: SurveySubmissionCacheWorker
  queue: default
  description: "This job updates the survey submission cache"
