defaults: &defaults
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  logger_level: 'INFO'
  rollbar:
    token: token
  mailer:
    :mailer_sender : 'Pulse Insights <welcome@pulseinsights.com>'
    :delivery_method : :smtp
    :default_url_options :
      :host : 'localhost:3000'
  jandj_ftp:
    host: c1sftp01.epsilon.com
    username:
    password:
  neutrogena_access_key: 'sample'
  neutrogena_endpoint: 'sample'
  open_ai:
    api_key: sample

development:
  <<: *defaults

test:
  <<: *defaults

develop:
  <<: *defaults

production:
  <<: *defaults
