#!/bin/bash

# Function to print usage
usage() {
    echo "Usage: $0 [-d directory] [-o output_file] [-m max_depth] [-i]"
    echo "  -d: Directory to scan (default: current directory)"
    echo "  -o: Output markdown file (default: directory_structure.md)"
    echo "  -m: Maximum depth to traverse (default: unlimited)"
    echo "  -i: Include hidden files/folders"
    exit 1
}

# Default values
DIR="."
OUTPUT="directory_structure.md"
MAX_DEPTH=""
INCLUDE_HIDDEN=false

# Parse command line options
while getopts "d:o:m:ih" opt; do
    case $opt in
        d) DIR="$OPTARG";;
        o) OUTPUT="$OPTARG";;
        m) MAX_DEPTH="-maxdepth $OPTARG";;
        i) INCLUDE_HIDDEN=true;;
        h) usage;;
        *) usage;;
    esac
done

# Check if directory exists
if [ ! -d "$DIR" ]; then
    echo "Error: Directory '$DIR' does not exist"
    exit 1
fi

# Function to generate tree structure
generate_tree() {
    local dir="$1"
    local prefix="$2"
    local depth="$3"
    
    # Get all items in directory
    local items=()
    if [ "$INCLUDE_HIDDEN" = true ]; then
        while IFS= read -r -d '' item; do
            items+=("$item")
        done < <(find "$dir" -maxdepth 1 -mindepth 1 -print0 | sort -z)
    else
        while IFS= read -r -d '' item; do
            items+=("$item")
        done < <(find "$dir" -maxdepth 1 -mindepth 1 -not -path '*/\.*' -print0 | sort -z)
    fi
    
    local count=${#items[@]}
    local index=0
    
    for item in "${items[@]}"; do
        index=$((index + 1))
        local basename=$(basename "$item")
        
        # Determine if last item
        if [ $index -eq $count ]; then
            local branch="└── "
            local extension="    "
        else
            local branch="├── "
            local extension="│   "
        fi
        
        # Check if directory or file
        if [ -d "$item" ]; then
            echo "${prefix}${branch}**${basename}/**" >> "$OUTPUT"
            
            # Recursively process subdirectory if within depth limit
            if [[ -z "$MAX_DEPTH" ]] || [[ $depth -lt ${MAX_DEPTH#-maxdepth } ]]; then
                generate_tree "$item" "${prefix}${extension}" $((depth + 1))
            fi
        else
            # Get file size
            local size=$(du -h "$item" 2>/dev/null | cut -f1)
            echo "${prefix}${branch}\`${basename}\` *(${size})*" >> "$OUTPUT"
        fi
    done
}

# Function to count files and directories
count_items() {
    local dir="$1"
    local find_opts=""
    
    if [ "$INCLUDE_HIDDEN" = false ]; then
        find_opts="-not -path '*/\.*'"
    fi
    
    if [ -n "$MAX_DEPTH" ]; then
        dir_count=$(eval "find '$dir' $MAX_DEPTH -type d $find_opts" | wc -l)
        file_count=$(eval "find '$dir' $MAX_DEPTH -type f $find_opts" | wc -l)
    else
        dir_count=$(eval "find '$dir' -type d $find_opts" | wc -l)
        file_count=$(eval "find '$dir' -type f $find_opts" | wc -l)
    fi
    
    # Subtract 1 from dir_count to exclude the root directory
    dir_count=$((dir_count - 1))
    
    echo "$dir_count:$file_count"
}

# Start generating markdown
echo "# Directory Structure" > "$OUTPUT"
echo "" >> "$OUTPUT"
echo "**Generated on:** $(date '+%Y-%m-%d %H:%M:%S')" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "**Root Directory:** \`$(realpath "$DIR")\`" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# Add summary
counts=$(count_items "$DIR")
dir_count=${counts%:*}
file_count=${counts#*:}
total_size=$(du -sh "$DIR" 2>/dev/null | cut -f1)

echo "## Summary" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "- **Total Directories:** $dir_count" >> "$OUTPUT"
echo "- **Total Files:** $file_count" >> "$OUTPUT"
echo "- **Total Size:** $total_size" >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "## Structure" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "\`\`\`" >> "$OUTPUT"
echo "$(basename "$DIR")/" >> "$OUTPUT"

# Generate the tree structure
generate_tree "$DIR" "" 1

echo "\`\`\`" >> "$OUTPUT"

# Add file type statistics
echo "" >> "$OUTPUT"
echo "## File Type Distribution" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "| Extension | Count |" >> "$OUTPUT"
echo "|-----------|-------|" >> "$OUTPUT"

# Get file extensions and count
if [ "$INCLUDE_HIDDEN" = true ]; then
    find "$DIR" $MAX_DEPTH -type f -name '*.*' 2>/dev/null | \
        sed 's/.*\.//' | sort | uniq -c | sort -rn | \
        while read count ext; do
            echo "| .$ext | $count |" >> "$OUTPUT"
        done
else
    find "$DIR" $MAX_DEPTH -type f -not -path '*/\.*' -name '*.*' 2>/dev/null | \
        sed 's/.*\.//' | sort | uniq -c | sort -rn | \
        while read count ext; do
            echo "| .$ext | $count |" >> "$OUTPUT"
        done
fi

echo "" >> "$OUTPUT"
echo "---" >> "$OUTPUT"
echo "*Generated by directory structure script*" >> "$OUTPUT"

echo "✅ Markdown file generated: $OUTPUT"