staging:
  adapter: postgresql
  password: "jjiampLIJ-bW2tD"
  username: pi_staging
  database: pi_staging
  port: 5432
  redis: "redis://127.0.0.1:6379"
  redis_host: "127.0.0.1"
  redis_port: 6379
  influxdb:
    database: "pi_staging"
    username: "pi"
    password: 'pi+2018!'
    hosts: ["10.142.0.13"]
    port: 8086
    use_ssl: false
    retry: 5
