# frozen_string_literal: true

# rubocop:disable Metrics/ModuleLength
# rubocop:disable Metrics/MethodLength
# rubocop:disable Style/WordArray

module GeoTargeting
  extend ActiveSupport::Concern

  module ClassMethods
    def dma
      [
        ['501',	'New York'],
        ['803',	'Los Angeles'],
        %w(602 Chicago),
        %w(504 Philadelphia),
        ['506',	'Boston (Manchester)'],
        ['807',	'San Francisco - Oakland - San Jose'],
        ['623',	'Dallas - Fort Worth'],
        ['511',	'Washington DC (Hagerstown)'],
        %w(524 Atlanta),
        %w(618 Houston),
        %w(505 Detroit),
        ['539',	'Tampa - Saint Petersburg (Sarasota)'],
        ['819',	'Seattle - Tacoma'],
        %w(753 Phoenix),
        ['613',	'Minneapolis - Saint Paul'],
        %w(510 Cleveland),
        ['528',	'Miami - Fort Lauderdale'],
        %w(751 Denver),
        ['862',	'Sacramento - Stockton - Modesto'],
        ['534',	'Orlando - Daytona Beach - Melbourne'],
        ['609',	'Saint Louis'],
        %w(508 Pittsburgh),
        ['820',	'Portland, OR'],
        %w(512 Baltimore),
        %w(527 Indianapolis),
        ['825',	'San Diego'],
        %w(517 Charlotte),
        ['533',	'Hartford & New Haven'],
        ['560',	'Raleigh - Durham (Fayetteville)'],
        %w(659 Nashville),
        ['616',	'Kansas City'],
        ['535',	'Columbus, OH'],
        %w(617 Milwaukee),
        %w(515 Cincinnati),
        ['567',	'Greenville - Spartansburg - Asheville - Anderson'],
        ['770',	'Salt Lake City'],
        ['641',	'San Antonio'],
        ['548',	'West Palm Beach - Fort Pierce'],
        ['563',	'Grand Rapids - Kalamazoo - Battle Creek'],
        ['630',	'Birmingham (Anniston and Tuscaloosa)'],
        ['566',	'Harrisburg - Lancaster - Lebanon - York'],
        ['544',	'Norfolk - Portsmouth - Newport News'],
        ['622',	'New Orleans'],
        %w(640 Memphis),
        ['650',	'Oklahoma City'],
        ['790',	'Albuquerque - Santa Fe'],
        ['518',	'Greensboro - High Point - Winston-Salem'],
        ['839',	'Las Vegas'],
        %w(514 Buffalo),
        %w(529 Louisville),
        ['521',	'Providence - New Bedford'],
        ['561',	'Jacksonville, Brunswick'],
        ['635',	'Austin, TX'],
        ['577',	'Wilkes Barre - Scranton'],
        ['532',	'Albany - Schenectady - Troy'],
        ['866',	'Fresno - Visalia'],
        ['693',	'Little Rock - Pine Bluff'],
        %w(557 Knoxville),
        %w(542 Dayton),
        ['556',	'Richmond - Petersburg'],
        %w(671 Tulsa),
        ['686',	'Mobile - Pensacola (Fort Walton Beach)'],
        %w(541 Lexington),
        ['564',	'Charleston-Huntington'],
        ['513',	'Flint - Saginaw - Bay City'],
        ['571',	'Fort Myers - Naples'],
        ['678',	'Wichita - Hutchinson'],
        ['573',	'Roanoke - Lynchburg'],
        ['658',	'Green Bay - Appleton'],
        %w(547 Toledo),
        ['789',	'Tucson (Sierra Vista)'],
        %w(744 Honolulu),
        ['679',	'Des Moines - Ames'],
        ['500',	'Portland - Auburn'],
        %w(652 Omaha),
        %w(555 Syracuse),
        ['619',	'Springfield, MO'],
        %w(881 Spokane),
        ['538',	'Rochester, NY'],
        ['632',	'Paducah - Cape Girardeau - Harrisburg - Mt Vernon'],
        %w(612 Shreveport),
        ['648',	'Champaign & Springfield - Decatur'],
        ['546',	'Columbia, SC'],
        ['691',	'Huntsville - Decatur (Florence)'],
        %w(669 Madison),
        %w(575 Chattanooga),
        ['588',	'South Bend - Elkhart'],
        ['637',	'Cedar Rapids - Waterloo & Dubuque'],
        ['718',	'Jackson, MS'],
        ['523',	'Burlington - Plattsburgh'],
        ['531',	'Tri-Cities, TN-VA'],
        ['636',	'Harlingen - Weslaco - Brownsville - McAllen'],
        ['625',	'Waco - Temple - Bryan'],
        ['682',	'Davenport - Rock Island - Moline'],
        ['716',	'Baton Rouge'],
        %w(507 Savannah),
        ['574',	'Johnstown - Altoona'],
        ['765',	'El Paso'],
        %w(649 Evansville),
        ['519',	'Charleston, SC'],
        %w(536 Youngstown),
        ['722',	'Lincoln & Hastings - Kearney'],
        ['670',	'Fort Smith - Fayetteville - Springdale - Rogers'],
        ['545',	'Greenville - New Bern - Washington'],
        ['509',	'Fort Wayne'],
        ['570',	'Florence - Myrtle Beach'],
        ['543',	'Springfield - Holyoke'],
        ['530',	'Tallahassee - Thomasville'],
        %w(551 Lansing),
        ['709',	'Tyler - Longview (Lufkin & Nacogdoches)'],
        %w(811 Reno),
        ['540',	'Traverse City - Cadillac'],
        ['725',	'Sioux Falls (Mitchell)'],
        %w(520 Augusta),
        ['698',	'Montgomery (Selma)'],
        ['675',	'Peoria - Bloomington'],
        ['724',	'Fargo - Valley City'],
        %w(757 Boise),
        %w(503 Macon),
        %w(801 Eugene),
        ['855',	'Santa Barbara - Santa Maria - San Luis Obispo'],
        ['702',	'La Crosse - Eau Claire'],
        ['642',	'Lafayette, LA'],
        ['828',	'Monterey - Salinas'],
        ['810',	'Yakima - Pasco - Richland - Kennewick'],
        ['673',	'Columbus - Tupelo - West Point'],
        %w(800 Bakersfield),
        ['600',	'Corpus Christi'],
        ['868',	'Chico - Redding'],
        %w(634 Amarillo),
        ['522',	'Columbus, GA'],
        %w(610 Rockford),
        ['705',	'Wausau - Rhinelander'],
        ['628',	'Monroe - El Dorado'],
        %w(605 Topeka),
        ['676',	'Duluth - Superior'],
        ['604',	'Columbia - Jefferson City'],
        %w(550 Wilmington),
        ['692',	'Beaumont - Port Arthur'],
        ['813',	'Medford - Klamath Falls'],
        %w(516 Erie),
        ['624',	'Sioux City'],
        ['627',	'Wichita Falls & Lawton'],
        ['603',	'Joplin - Pittsburg'],
        %w(651 Lubbock),
        ['525',	'Albany, GA'],
        %w(576 Salisbury),
        ['559',	'Bluefield - Beckley - Oak Hill'],
        ['581',	'Terre Haute'],
        %w(537 Bangor),
        ['611',	'Rochester - Mason City - Austin'],
        ['804',	'Palm Springs'],
        ['554',	'Wheeling - Steubenville'],
        %w(743 Anchorage),
        %w(502 Binghamton),
        ['656',	'Panama City'],
        ['746',	'Biloxi - Gulfport'],
        ['633',	'Odessa - Midland'],
        ['687',	'Minot - Bismarck - Dickinson'],
        ['657',	'Sherman, TX - Ada, OK'],
        %w(592 Gainesville),
        ['758',	'Idaho Falls - Pocatello'],
        ['662',	'Abilene - Sweetwater'],
        ['598',	'Clarksburg - Weston'],
        %w(526 Utica),
        ['710',	'Hattiesburg - Laurel'],
        %w(762 Missoula),
        ['717',	'Quincy - Hannibal - Keokuk'],
        ['771',	'Yuma - El Centro'],
        %w(756 Billings),
        %w(606 Dothan),
        %w(565 Elmira),
        ['639',	'Jackson, TN'],
        ['643',	'Lake Charles'],
        ['644',	'Alexandria, LA'],
        ['764',	'Rapid City'],
        %w(549 Watertown),
        %w(734 Jonesboro),
        %w(553 Marquette),
        %w(569 Harrisonburg),
        ['647',	'Greenwood - Greenville'],
        ['736',	'Bowling Green'],
        %w(711 Meridian),
        %w(558 Lima),
        %w(584 Charlottesville),
        ['773',	'Grand Junction - Montrose'],
        %w(749 Laredo),
        ['755',	'Great Falls'],
        %w(597 Parkersburg),
        ['582',	'Lafayette, IN'],
        ['760',	'Twin Falls'],
        ['754',	'Butte - Bozeman'],
        %w(802 Eureka),
        ['759',	'Cheyenne - Scottsbluff'],
        ['821',	'Bend, OR'],
        ['661',	'San Angelo'],
        ['767',	'Casper - Riverton'],
        ['631',	'Ottumwa - Kirksville'],
        %w(737 Mankato),
        ['638',	'Saint Joseph'],
        %w(596 Zanesville),
        %w(745 Fairbanks),
        ['552',	'Presque Isle'],
        %w(626 Victoria),
        %w(766 Helena),
        %w(747 Juneau),
        %w(583 Alpena),
        ['740',	'North Platte'],
        %w(798 Glendive)
      ].map(&:reverse).sort { |a, b| a[0] <=> b[0] }
    end

    def geoip_states
      %w(Alaska Alabama Arkansas American\ Samoa Arizona California Colorado Connecticut District\ of\ Columbia Delaware Florida Georgia Guam Hawaii
         Iowa Idaho Illinois Indiana Kansas Kentucky Louisiana Massachusetts Maryland Maine Michigan Minnesota Missouri Mississippi Montana
         North\ Carolina North\ Dakota Nebraska New\ Hampshire New\ Jersey New\ Mexico Nevada New\ York Ohio Oklahoma Oregon Pennsylvania Puerto\ Rico
         Rhode\ Island South\ Carolina South\ Dakota Tennessee Texas Utah Virginia Virgin\ Islands Vermont Washington Wisconsin West\ Virginia
         Wyoming).freeze
    end

    # rubocop:disable Metrics/CollectionLiteralLength
    # TODO: Put these someplace else
    def geoip_countries
      ["Rwanda",
       "Somalia",
       "Yemen",
       "Iraq",
       "Saudi Arabia",
       "Iran",
       "Cyprus",
       "Tanzania",
       "Syria",
       "Armenia",
       "Kenya",
       "Congo",
       "Djibouti",
       "Uganda",
       "Central African Republic",
       "Seychelles",
       "Hashemite Kingdom of Jordan",
       "Lebanon",
       "Kuwait",
       "Oman",
       "Qatar",
       "Bahrain",
       "United Arab Emirates",
       "Israel",
       "Turkey",
       "Ethiopia",
       "Eritrea",
       "Egypt",
       "Sudan",
       "Greece",
       "Burundi",
       "Estonia",
       "Latvia",
       "Azerbaijan",
       "Republic of Lithuania",
       "Svalbard and Jan Mayen",
       "Georgia",
       "Republic of Moldova",
       "Belarus",
       "Finland",
       "Հland",
       "Ukraine",
       "Macedonia",
       "Hungary",
       "Bulgaria",
       "Albania",
       "Poland",
       "Romania",
       "Kosovo",
       "Zimbabwe",
       "Zambia",
       "Comoros",
       "Malawi",
       "Lesotho",
       "Botswana",
       "Mauritius",
       "Swaziland",
       "Rթunion",
       "South Africa",
       "Mayotte",
       "Mozambique",
       "Madagascar",
       "Afghanistan",
       "Pakistan",
       "Bangladesh",
       "Turkmenistan",
       "Tajikistan",
       "Sri Lanka",
       "Bhutan",
       "India",
       "Maldives",
       "British Indian Ocean Territory",
       "Nepal",
       "Myanmar [Burma]",
       "Uzbekistan",
       "Kazakhstan",
       "Kyrgyzstan",
       "French Southern Territories",
       "Heard Island and McDonald Islands",
       "Cocos [Keeling] Islands",
       "Palau",
       "Vietnam",
       "Thailand",
       "Indonesia",
       "Laos",
       "Taiwan",
       "Philippines",
       "Malaysia",
       "China",
       "Hong Kong",
       "Brunei",
       "Macao",
       "Cambodia",
       "Republic of Korea",
       "Japan",
       "North Korea",
       "Singapore",
       "Cook Islands",
       "East Timor",
       "Russia",
       "Mongolia",
       "Australia",
       "Christmas Island",
       "Marshall Islands",
       "Federated States of Micronesia",
       "Papua New Guinea",
       "Solomon Islands",
       "Tuvalu",
       "Nauru",
       "Vanuatu",
       "New Caledonia",
       "Norfolk Island",
       "New Zealand",
       "Fiji",
       "Libya",
       "Cameroon",
       "Senegal",
       "Republic of the Congo",
       "Portugal",
       "Liberia",
       "Ivory Coast",
       "Ghana",
       "Equatorial Guinea",
       "Nigeria",
       "Burkina Faso",
       "Togo",
       "Guinea-Bissau",
       "Mauritania",
       "Benin",
       "Gabon",
       "Sierra Leone",
       "São Tomé e Príncipe",
       "Gibraltar",
       "Gambia",
       "Guinea",
       "Chad",
       "Niger",
       "Mali",
       "Western Sahara",
       "Tunisia",
       "Spain",
       "Morocco",
       "Malta",
       "Algeria",
       "Faroe Islands",
       "Denmark",
       "Iceland",
       "United Kingdom",
       "Switzerland",
       "Sweden",
       "Netherlands",
       "Austria",
       "Belgium",
       "Germany",
       "Luxembourg",
       "Ireland",
       "Monaco",
       "France",
       "Andorra",
       "Liechtenstein",
       "Jersey",
       "Isle of Man",
       "Guernsey",
       "Slovakia",
       "Czechia",
       "Norway",
       "Vatican City",
       "San Marino",
       "Italy",
       "Slovenia",
       "Montenegro",
       "Croatia",
       "Bosnia and Herzegovina",
       "Angola",
       "Namibia",
       "Saint Helena",
       "Bouvet Island",
       "Barbados",
       "Cabo Verde",
       "Guyana",
       "French Guiana",
       "Suriname",
       "Saint Pierre and Miquelon",
       "Greenland",
       "Paraguay",
       "Uruguay",
       "Brazil",
       "Falkland Islands",
       "South Georgia and the South Sandwich Islands",
       "Jamaica",
       "Dominican Republic",
       "Cuba",
       "Martinique",
       "Bahamas",
       "Bermuda",
       "Anguilla",
       "Trinidad and Tobago",
       "St Kitts and Nevis",
       "Dominica",
       "Antigua and Barbuda",
       "Saint Lucia",
       "Turks and Caicos Islands",
       "Aruba",
       "British Virgin Islands",
       "Saint Vincent and the Grenadines",
       "Montserrat",
       "Saint Martin",
       "Saint-Barthélemy",
       "Guadeloupe",
       "Grenada",
       "Cayman Islands",
       "Belize",
       "El Salvador",
       "Guatemala",
       "Honduras",
       "Nicaragua",
       "Costa Rica",
       "Venezuela",
       "Ecuador",
       "Colombia",
       "Panama",
       "Haiti",
       "Argentina",
       "Chile",
       "Bolivia",
       "Peru",
       "Mexico",
       "French Polynesia",
       "Pitcairn Islands",
       "Kiribati",
       "Tokelau",
       "Tonga",
       "Wallis and Futuna",
       "Samoa",
       "Niue",
       "Northern Mariana Islands",
       "Guam",
       "Puerto Rico",
       "U.S. Virgin Islands",
       "U.S. Minor Outlying Islands",
       "American Samoa",
       "Canada",
       "United States",
       "Palestine",
       "Serbia",
       "Antarctica",
       "Sint Maarten",
       "Curaçao",
       "Bonaire, Sint Eustatius, and Saba",
       "South Sudan"].freeze
    end
  end
end
