develop:
  adapter: postgresql
  password: "jjiampLIJ-bW2tD"
  username: pi_develop
  database: pi_develop
  host: localhost
  port: 5432
  rack-host: "127.0.0.1"
  redis: "redis://127.0.0.1:6379"
  redis_host: "127.0.0.1"
  redis_port: 6379
  influxdb:
    database: "pi_develop"
    username: "pi"
    password: 'pi+2018!'
    hosts: ["127.0.0.1"]
    port: 8086
    use_ssl: false
    retry: 5
