regularly_analyze_free_text_answers:
  every: "10m"
  class: RegularlyAnalyzeFreeTextAnswers
  queue: default
  description: "This job will regularly analyze free text answers"
trim_sessions:
  every: "30d"
  class: TrimSessionsWorker
  queue: default
  description: "This job will trim session every 30 days"
scheduled_report:
  cron: "0 10 * * *"
  class: ScheduledReportWorker
  queue: default
  description: "This job will daily send report if scheduled"
deactivate_users:
  cron: "0 0 * * *"
  class: DeactivateExpiredUsersWorker
  queue: default
  description: "This job will check expired users and deactivate them daily"
survey_submission_cache:
  cron: '*/10 * * * *'
  class: SurveySubmissionCacheWorker
  queue: default
  description: "This job updates the survey submission cache every 10 minutes"
qrvey_full_insert:
  every: '1m'
  class: Qrvey::FullInsertWorker
  queue: default
  description: "This worker uploads to an S3 bucket a CSV file Qrvey's data sync process consumes every minute"
qrvey_partial_update:
  every: '5m'
  class: Qrvey::PartialUpdateWorker
  queue: default
  description: "This worker sends metadata updates to Qrvey's Push API endpoint every 5 minutes"
complete_expired_surveys:
  cron: '0 * * * *'
  class: CompleteExpiredSurveysWorker
  queue: default
  description: "This job checks for live surveys with expired end dates and marks them as complete every hour"
