production:
  adapter: postgresql_makara
  makara:
    disable_blacklist: true
    sticky: false
    connections:
      - role: master
        host: 10.142.0.8
        port: 5433
      - role: slave
        host: 127.0.0.1
        port: 5433
  database: pi
  username: pi
  password: HmXB}hFBx6Mjz6]#@dpY
  pool: 16
  idle_timeout: 10
  port: 5433
  redis: "redis://127.0.0.1:6379"
  rack-host: 127.0.0.1
  redis_host: 127.0.0.1
  redis_port: 6379
  influxdb:
    database: "pi_production"
    username: "pi"
    password: 'pi+2018!'
    hosts: ["10.142.0.13"]
    port: 8086
    use_ssl: false
    retry: 5
