# frozen_string_literal: true
#
# Based on autogenerated spec provided by Selenium IDE
# https://gitlab.ekohe.com/ekohe/pulseinsights/pi/-/wikis/Testing/Visual-Regression-Testing

require "percy"
require "spec_helper"

require_relative "../live_survey_spec_helper"
require_relative "../surveys/surveys_spec_helper"

include LiveSurveySpecHelper
include SurveysSpecHelper

# rubocop:disable RSpec/DescribeClass
describe "Survey 4115" do
  let(:driver) { Selenium::WebDriver.for :chrome }
  let(:account_identifier) { "PI-08917801" }
  let(:survey_id) { 4115 }
  let(:snapshot_id) { "#{account_identifier} (#{survey_id}) Dealer Site | Feedback Tab" }
  let(:client_url) { "https://www.bobcat.com/na/en?pi_live_preview=true&pi_present=#{survey_id}" }
  let(:tag_js_version) { "1.0.0" }

  it "visits the page and takes the survey" do
    visit_client_site

    driver.manage.window.resize_to(1706, 1033)

    take_screenshot("Overlay taking up portion of screen")

    find_element({css: ".\\_pi_all_questions_submit_button"}).click

    take_screenshot("\"Please fill answers\" empty error message")

    find_element({css: "li:nth-child(4) label"}).click
    find_element({css: ".\\_pi_free_text_question_field"}).click

    very_long_input_string = "test neorhgoeirhnbosldnfbofnborlfbnoifbnofbnotwb\
pwrtbpthbithbopihrbphbirthbopithbpohtrboiprthborhbpoeibhrbhrpeobhporiehb\
peroihbropeihbroiehbporebhoirebhbprbhrpeoibhhbpoeihbpiorheopbhrpeohbeporbphbpeo1"
    find_element({css: ".\\_pi_free_text_question_field"}).send_keys(very_long_input_string)

    take_screenshot("Full text field")
    find_element({css: ".\\_pi_all_questions_submit_button"}).click

    take_screenshot("Thank You message")
  end
end
