# frozen_string_literal: true
#
# Based on autogenerated spec provided by Selenium IDE
# https://gitlab.ekohe.com/ekohe/pulseinsights/pi/-/wikis/Testing/Visual-Regression-Testing

require "percy"
require "spec_helper"

require_relative "../live_survey_spec_helper"
require_relative "../surveys/surveys_spec_helper"

include LiveSurveySpecHelper
include SurveysSpecHelper

# rubocop:disable RSpec/DescribeClass
describe "Survey 5499" do
  let(:driver) { Selenium::WebDriver.for :chrome }
  let(:account_identifier) { "PI-29512454" }
  let(:survey_id) { 5499 }
  let(:snapshot_id) { "#{account_identifier} (#{survey_id}) Fraud Claims | Submission Business | 2021.9" }
  let(:client_url) { "https://www.verizon.com/about/parenting/parenting-in-a-digital-world?pi_live_preview=true&pi_present=#{survey_id}" }
  let(:tag_js_version) { "1.0.0" }

  it "visits the page and takes the survey" do
    visit_client_site

    driver.manage.window.resize_to(1706, 1033)

    # Click cookie banner (Accept All)
    cookie_banner = find_element({id: "onetrust-accept-btn-handler"})
    cookie_banner&.click # Sometimes it's not rendered

    take_screenshot("Bottom bar single choice question")

    find_element({css: "li:nth-child(3) label"}).click

    find_element({css: ".\\_pi_free_text_question_field"}).send_keys("test")

    take_screenshot("Bottom bar free text question")

    find_element({css: ".\\_pi_free_text_question_submit_button"}).click
  end
end
