require: rubocop-rspec

inherit_mode:
  merge:
    - AllowedNames

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  DisplayCopNames: true
  Exclude:
    - '**/*.yml'
    - 'db/**/*'
    - 'config/**/*'
    - 'doc/**/*'
    - 'deployment/**/*'
    - 'bin/**/*'
    - 'spec/spec_helper.rb'
    - 'cache/**/*'
    - 'node_modules/**/*'
    - 'vendor/ruby/**/*'

Naming/HeredocDelimiterCase:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames:
    - 'js'
    - 'e'
    - 'p'

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Layout/HeredocIndentation:
  Enabled: false

Layout/IndentationStyle:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/LineLength:
  Max: 160
  AllowedPatterns: ["let!?"]

Layout/ElseAlignment:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/RescueEnsureAlignment:
  Enabled: false

Style/FormatString:
  Enabled: false

Layout/MultilineHashBraceLayout:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/FloatDivision:
  Enabled: false

Style/RedundantSort:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - spec/**/*.rb

Metrics/ClassLength:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/MissingCopEnableDirective:
  Enabled: false

Layout/EmptyLinesAroundAccessModifier:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%W': ()
    '%w': ()
    '%i': ()

Style/BlockComments:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MixinGrouping:
  Enabled: false

Style/AndOr:
  EnforcedStyle: conditionals

Metrics/MethodLength:
  Max: 30

Layout/CaseIndentation:
  # Valid values are: case, end
  EnforcedStyle: end
  IndentOneStep: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Metrics/AbcSize:
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 15

Metrics/ParameterLists:
  Max: 10
  Exclude:
    - app/workers/native_create_impression_worker.rb

Lint/UselessAssignment:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*.rb

Lint/SymbolConversion:
  EnforcedStyle: consistent

Security/YAMLLoad:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/ExampleLength:
  Max: 35

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/DescribeClass:
  Exclude:
    - spec/surveys/*.rb
    - spec/integration/*/*.rb

RSpec/ReceiveCounts:
  Enabled: false

RSpec/ReturnFromStub:
  Enabled: false

RSpec/ExpectChange:
  Enabled: false

FactoryBot/CreateList:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

# We use a lot of helper methods which contain expect statements
# Maybe it's a bad practice, but it'd be a lot to untangle.
RSpec/NoExpectationExample:
  Enabled: false

# We need to review our assumptions around ENV var access
# before enabling this.
Style/FetchEnvVar:
  Enabled: false

# https://github.com/rubocop/rubocop/issues/9947
Naming/InclusiveLanguage:
  Enabled: false

# Rack app is a detached process during the tests, so the response is an
# instance of Net::HTTPOK instead of classes like ActionDispatch::TestResponse
RSpec/Rails/HaveHttpStatus:
  Exclude:
    - 'spec/rack/**/*'
