# frozen_string_literal: true
source 'https://rubygems.org'

gem 'influxdb'
gem 'pg'
gem 'rails', "~>7.0.0"
gem 'sdoc', group: :doc
gem 'thin', require: false

# SSO
gem 'omniauth'
gem 'omniauth-google-oauth2'
gem 'omniauth-multi-provider'
gem 'omniauth-rails_csrf_protection'
gem 'omniauth-saml'

# Authentication
gem 'devise'
gem 'devise-two-factor'
gem 'rqrcode'

# JS / CSS
gem 'bootstrap-sass'
gem 'chosen-rails'
gem 'haml-rails'
gem 'jquery-rails'
gem 'sass-rails'
gem 'terser', '~> 1.2'
gem 'turbolinks'

# Other
gem 'audited'
gem 'awesome_print'
gem 'aws-sdk'
gem 'carrierwave'
gem 'caxlsx'
gem 'caxlsx_rails'
gem 'combine_pdf'
gem 'deep_cloneable'
gem 'ffaker'
gem 'fog-aws'
gem 'image_processing'
gem 'rest-client'
gem 'selenium-webdriver'
gem 'simple_form'
gem 'useragent'
gem 'voight_kampff'
gem 'wicked_pdf'
gem 'will_paginate'
# Upgrading this requires a change on each server that uses it.
# See https://gitlab.ekohe.com/ekohe/pulseinsights/pi/-/issues/2974#note_1304261 for an example
gem 'wkhtmltopdf-binary', '0.12.6.9'

# PI client integration specific
gem 'google-cloud-storage'
gem 'hubspot-api-client'
gem 'klaviyo-api-sdk'
gem 'net-sftp'

# Sidekiq
gem 'sidekiq'
gem 'sidekiq-failures'
gem 'sidekiq-scheduler'
gem 'sinatra', require: false

# Rubocop
gem 'rubocop'
gem 'rubocop-rspec'

# Gem vulnerability auditing
# We rely on undocumented features (see BundleAuditWorker), so
# upgrade this with caution.
gem 'bundler-audit', '0.9.1'

# Exception and Performance trackers
group :staging, :production do
  gem 'newrelic_rpm'
end
gem 'rollbar'

gem 'rake_text'

gem 'sanitize_email'

gem 'google-api-client' # Google Slides and Google Drive
gem 'google-cloud-language'
gem 'google-cloud-translate'

gem 'activerecord-session_store'

gem "anthropic"
gem "ruby-openai"
gem "tiktoken_ruby"

# React support
gem 'react-rails'
gem 'webpacker', '6.0.0.rc.6' # Must match @rails/webpacker version

gem 'rack-attack'

group :assets do
  gem 'coffee-rails'
end

group :test do
  gem 'rails-controller-testing'
  gem 'rspec-sidekiq'
  gem 'shoulda-matchers'
  gem 'webmock'
end

group :development, :test do
  gem 'childprocess'
  gem 'database_rewinder'
  gem 'factory_bot_rails'
  gem 'guard-rspec'
  gem 'percy-selenium'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'rspec-rails'
end

group :development, :deployment do
  gem 'capistrano'
  gem 'capistrano-bundler'
  gem 'capistrano-rails'
  gem 'capistrano-rails-console'
  gem 'capistrano-rvm'
end

group :development do
  gem 'annotate'
  gem 'brakeman', require: false
  gem 'rails-erd'
  gem 'scout_apm'
  gem 'spring'
end

gem 'makara'
gem 'puma'
gem 'sprockets-rails'

gem 'dry-schema'
gem "rdoc", "~>6.3.1"
gem 'redis'
