scheduled_report:
  # every 10 minutes
  cron: '*/10 * * * *'
  class: ScheduledReportWorker
  queue: default
  description: "This job processes all the upcoming scheduled reports that are not in progress"

survey_submission_cache:
  cron: '*/10 * * * *'
  class: SurveySubmissionCacheWorker
  queue: default
  description: "This job updates the survey submission cache every 10 minutes"

periodic_report_checkup_worker:
  cron: '50 23 * * *'
  class: PeriodicReportWorkers::CheckupWorker
  queue: default
  description: "This job checks for failed periodic reports and notifies us when one has failed"
